@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.rustysnail.terrafirmathings.common.entity;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
